#############################################################################
# Makefile for building: EKG
# Generated by qmake (2.01a) (Qt 4.7.0) on: Fri Jul 1 07:52:05 2011
# Project:  EKG.pro
# Template: app
# Command: /usr/share/qtsdk-2010.05/qt/bin/qmake -spec /usr/share/qtsdk-2010.05/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile EKG.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -mtune=core2 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qtsdk-2010.05/qt/mkspecs/linux-g++-64 -I. -I/usr/share/qtsdk-2010.05/qt/include/QtCore -I/usr/share/qtsdk-2010.05/qt/include/QtGui -I/usr/share/qtsdk-2010.05/qt/include -I/usr/include/qwt-qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/usr/share/qtsdk-2010.05/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/share/qtsdk-2010.05/qt/lib -lqwt-qt4 -lwfdb -lm -lfann -ltbb -lfftw3 -lQtGui -L/usr/share/qtsdk-2010.05/qt/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/share/qtsdk-2010.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ekgwindow.cpp \
		rythmchk.cpp \
		qrsfilt.cpp \
		qrsdet2.cpp \
		postclas.cpp \
		noisechk.cpp \
		match.cpp \
		classify.cpp \
		bdac.cpp \
		analbeat.cpp \
		sigdetect.cpp \
		wekawriter.cpp \
		diseawriter.cpp \
		r_feature.cpp \
		listrw.cpp \
		ekgsignal.cpp \
		GButton.cpp \
		ekgscan.cpp \
		ekgnn.cpp moc_ekgwindow.cpp \
		moc_GButton.cpp \
		qrc_EKG.cpp
OBJECTS       = main.o \
		ekgwindow.o \
		rythmchk.o \
		qrsfilt.o \
		qrsdet2.o \
		postclas.o \
		noisechk.o \
		match.o \
		classify.o \
		bdac.o \
		analbeat.o \
		sigdetect.o \
		wekawriter.o \
		diseawriter.o \
		r_feature.o \
		listrw.o \
		ekgsignal.o \
		GButton.o \
		ekgscan.o \
		ekgnn.o \
		moc_ekgwindow.o \
		moc_GButton.o \
		qrc_EKG.o
DIST          = /usr/share/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/usr/share/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		EKG.pro
QMAKE_TARGET  = EKG
DESTDIR       = 
TARGET        = EKG

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EKG.pro  /usr/share/qtsdk-2010.05/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/usr/share/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/usr/share/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		/usr/share/qtsdk-2010.05/qt/lib/libQtGui.prl \
		/usr/share/qtsdk-2010.05/qt/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qtsdk-2010.05/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile EKG.pro
/usr/share/qtsdk-2010.05/qt/mkspecs/common/g++.conf:
/usr/share/qtsdk-2010.05/qt/mkspecs/common/unix.conf:
/usr/share/qtsdk-2010.05/qt/mkspecs/common/linux.conf:
/usr/share/qtsdk-2010.05/qt/mkspecs/qconfig.pri:
/usr/share/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/debug.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/default_post.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/qt.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/moc.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/resources.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/uic.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/yacc.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/lex.prf:
/usr/share/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf:
/usr/share/qtsdk-2010.05/qt/lib/libQtGui.prl:
/usr/share/qtsdk-2010.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qtsdk-2010.05/qt/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile EKG.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/EKG1.0.0 || $(MKDIR) .tmp/EKG1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EKG1.0.0/ && $(COPY_FILE) --parents ekgwindow.h rythmchk.h qrsdet.h postclas.h match.h inputs.h ecgcodes.h bdac.h analbeat.h sigdetect.h wekawriter.h diseawriter.h r_feature.h listrw.h ekgsignal.h GButton.h ekgscan.h ekgnn.h .tmp/EKG1.0.0/ && $(COPY_FILE) --parents EKG.qrc .tmp/EKG1.0.0/ && $(COPY_FILE) --parents main.cpp ekgwindow.cpp rythmchk.cpp qrsfilt.cpp qrsdet2.cpp postclas.cpp noisechk.cpp match.cpp classify.cpp bdac.cpp analbeat.cpp sigdetect.cpp wekawriter.cpp diseawriter.cpp r_feature.cpp listrw.cpp ekgsignal.cpp GButton.cpp ekgscan.cpp ekgnn.cpp .tmp/EKG1.0.0/ && (cd `dirname .tmp/EKG1.0.0` && $(TAR) EKG1.0.0.tar EKG1.0.0 && $(COMPRESS) EKG1.0.0.tar) && $(MOVE) `dirname .tmp/EKG1.0.0`/EKG1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EKG1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ekgwindow.cpp moc_GButton.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ekgwindow.cpp moc_GButton.cpp
moc_ekgwindow.cpp: ekgnn.h \
		ekgscan.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		ekgwindow.h
	/usr/share/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) ekgwindow.h -o moc_ekgwindow.cpp

moc_GButton.cpp: ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		GButton.h
	/usr/share/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) GButton.h -o moc_GButton.cpp

compiler_rcc_make_all: qrc_EKG.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_EKG.cpp
qrc_EKG.cpp: EKG.qrc \
		Image/B1.png \
		Image/D.png \
		Image/B2.png \
		Image/R1.png \
		Image/B3.png \
		Image/R2.png \
		Image/R3.png \
		Image/O1.png \
		Image/O2.png \
		Image/Alert.png \
		Image/O3.png \
		Image/icon.png \
		Image/G1.png \
		Image/G2.png \
		Image/G3.png \
		Image/Shadow.png \
		Image/D1.png
	/usr/share/qtsdk-2010.05/qt/bin/rcc -name EKG EKG.qrc -o qrc_EKG.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp ekgwindow.h \
		ekgnn.h \
		ekgscan.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ekgwindow.o: ekgwindow.cpp ekgwindow.h \
		ekgnn.h \
		ekgscan.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		inputs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ekgwindow.o ekgwindow.cpp

rythmchk.o: rythmchk.cpp qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rythmchk.o rythmchk.cpp

qrsfilt.o: qrsfilt.cpp qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrsfilt.o qrsfilt.cpp

qrsdet2.o: qrsdet2.cpp qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrsdet2.o qrsdet2.cpp

postclas.o: postclas.cpp bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		ecgcodes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o postclas.o postclas.cpp

noisechk.o: noisechk.cpp qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o noisechk.o noisechk.cpp

match.o: match.cpp bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o match.o match.cpp

classify.o: classify.cpp qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		bdac.h \
		match.h \
		rythmchk.h \
		analbeat.h \
		postclas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o classify.o classify.cpp

bdac.o: bdac.cpp bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bdac.o bdac.cpp

analbeat.o: analbeat.cpp bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analbeat.o analbeat.cpp

sigdetect.o: sigdetect.cpp sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sigdetect.o sigdetect.cpp

wekawriter.o: wekawriter.cpp wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wekawriter.o wekawriter.cpp

diseawriter.o: diseawriter.cpp diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diseawriter.o diseawriter.cpp

r_feature.o: r_feature.cpp r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o r_feature.o r_feature.cpp

listrw.o: listrw.cpp listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o listrw.o listrw.cpp

ekgsignal.o: ekgsignal.cpp ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ekgsignal.o ekgsignal.cpp

GButton.o: GButton.cpp GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GButton.o GButton.cpp

ekgscan.o: ekgscan.cpp ekgscan.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ekgscan.o ekgscan.cpp

ekgnn.o: ekgnn.cpp ekgnn.h \
		ekgscan.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		bdac.h \
		qrsdet.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ekgnn.o ekgnn.cpp

moc_ekgwindow.o: moc_ekgwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ekgwindow.o moc_ekgwindow.cpp

moc_GButton.o: moc_GButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GButton.o moc_GButton.cpp

qrc_EKG.o: qrc_EKG.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_EKG.o qrc_EKG.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

