#############################################################################
# Makefile for building: EKG
# Generated by qmake (2.01a) (Qt 4.7.0) on: Fri Jul 22 08:43:25 2011
# Project:  EKG.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile EKG.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -mtune=core2 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qwt-qt4 -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lqwt-qt4 -lwfdb -lm -lfann -lfftw3 -lksane -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ekgwindow.cpp \
		sigdetect.cpp \
		wekawriter.cpp \
		diseawriter.cpp \
		r_feature.cpp \
		listrw.cpp \
		ekgsignal.cpp \
		GButton.cpp \
		ekgscan.cpp \
		qrsdet.cpp \
		EKGFramWork.cpp \
		ekgimagep.cpp \
		qscan.cpp \
		ekgnn.cpp \
		nnframwork.cpp moc_ekgwindow.cpp \
		moc_GButton.cpp \
		moc_ekgscan.cpp \
		moc_qscan.cpp \
		moc_ekgnn.cpp \
		moc_nnframwork.cpp \
		qrc_EKG.cpp
OBJECTS       = main.o \
		ekgwindow.o \
		sigdetect.o \
		wekawriter.o \
		diseawriter.o \
		r_feature.o \
		listrw.o \
		ekgsignal.o \
		GButton.o \
		ekgscan.o \
		qrsdet.o \
		EKGFramWork.o \
		ekgimagep.o \
		qscan.o \
		ekgnn.o \
		nnframwork.o \
		moc_ekgwindow.o \
		moc_GButton.o \
		moc_ekgscan.o \
		moc_qscan.o \
		moc_ekgnn.o \
		moc_nnframwork.o \
		qrc_EKG.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		EKG.pro
QMAKE_TARGET  = EKG
DESTDIR       = 
TARGET        = EKG

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EKG.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile EKG.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile EKG.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/EKG1.0.0 || $(MKDIR) .tmp/EKG1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EKG1.0.0/ && $(COPY_FILE) --parents ekgwindow.h rythmchk.h sigdetect.h wekawriter.h diseawriter.h r_feature.h listrw.h ekgsignal.h GButton.h ekgscan.h header.h qrsdet.h EKGFramWork.h ekgimagep.h qscan.h ekgnn.h nnframwork.h .tmp/EKG1.0.0/ && $(COPY_FILE) --parents EKG.qrc .tmp/EKG1.0.0/ && $(COPY_FILE) --parents main.cpp ekgwindow.cpp sigdetect.cpp wekawriter.cpp diseawriter.cpp r_feature.cpp listrw.cpp ekgsignal.cpp GButton.cpp ekgscan.cpp qrsdet.cpp EKGFramWork.cpp ekgimagep.cpp qscan.cpp ekgnn.cpp nnframwork.cpp .tmp/EKG1.0.0/ && (cd `dirname .tmp/EKG1.0.0` && $(TAR) EKG1.0.0.tar EKG1.0.0 && $(COMPRESS) EKG1.0.0.tar) && $(MOVE) `dirname .tmp/EKG1.0.0`/EKG1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EKG1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ekgwindow.cpp moc_GButton.cpp moc_ekgscan.cpp moc_qscan.cpp moc_ekgnn.cpp moc_nnframwork.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ekgwindow.cpp moc_GButton.cpp moc_ekgscan.cpp moc_qscan.cpp moc_ekgnn.cpp moc_nnframwork.cpp
moc_ekgwindow.cpp: nnframwork.h \
		qrsdet.h \
		ekgnn.h \
		qscan.h \
		ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		ekgwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ekgwindow.h -o moc_ekgwindow.cpp

moc_GButton.cpp: ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		GButton.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) GButton.h -o moc_GButton.cpp

moc_ekgscan.cpp: ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		ekgscan.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ekgscan.h -o moc_ekgscan.cpp

moc_qscan.cpp: ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		qscan.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qscan.h -o moc_qscan.cpp

moc_ekgnn.cpp: qscan.h \
		ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		ekgnn.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ekgnn.h -o moc_ekgnn.cpp

moc_nnframwork.cpp: qrsdet.h \
		ekgnn.h \
		qscan.h \
		ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h \
		nnframwork.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) nnframwork.h -o moc_nnframwork.cpp

compiler_rcc_make_all: qrc_EKG.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_EKG.cpp
qrc_EKG.cpp: EKG.qrc \
		Image/B1.png \
		Image/D.png \
		Image/B2.png \
		Image/R1.png \
		Image/B3.png \
		Image/R2.png \
		Image/R3.png \
		Image/O1.png \
		Image/O2.png \
		Image/Alert.png \
		Image/O3.png \
		Image/icon.png \
		Image/G1.png \
		Image/G2.png \
		Image/G3.png \
		Image/Shadow.png \
		Image/D1.png
	/usr/bin/rcc -name EKG EKG.qrc -o qrc_EKG.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp ekgwindow.h \
		nnframwork.h \
		qrsdet.h \
		ekgnn.h \
		qscan.h \
		ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ekgwindow.o: ekgwindow.cpp ekgwindow.h \
		nnframwork.h \
		qrsdet.h \
		ekgnn.h \
		qscan.h \
		ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ekgwindow.o ekgwindow.cpp

sigdetect.o: sigdetect.cpp sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sigdetect.o sigdetect.cpp

wekawriter.o: wekawriter.cpp wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wekawriter.o wekawriter.cpp

diseawriter.o: diseawriter.cpp diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diseawriter.o diseawriter.cpp

r_feature.o: r_feature.cpp r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o r_feature.o r_feature.cpp

listrw.o: listrw.cpp listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o listrw.o listrw.cpp

ekgsignal.o: ekgsignal.cpp ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ekgsignal.o ekgsignal.cpp

GButton.o: GButton.cpp GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GButton.o GButton.cpp

ekgscan.o: ekgscan.cpp ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ekgscan.o ekgscan.cpp

qrsdet.o: qrsdet.cpp qrsdet.h \
		ekgnn.h \
		qscan.h \
		ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrsdet.o qrsdet.cpp

EKGFramWork.o: EKGFramWork.cpp EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EKGFramWork.o EKGFramWork.cpp

ekgimagep.o: ekgimagep.cpp ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ekgimagep.o ekgimagep.cpp

qscan.o: qscan.cpp qscan.h \
		ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qscan.o qscan.cpp

ekgnn.o: ekgnn.cpp ekgnn.h \
		qscan.h \
		ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ekgnn.o ekgnn.cpp

nnframwork.o: nnframwork.cpp nnframwork.h \
		qrsdet.h \
		ekgnn.h \
		qscan.h \
		ekgscan.h \
		ekgimagep.h \
		GButton.h \
		ekgsignal.h \
		listrw.h \
		r_feature.h \
		diseawriter.h \
		wekawriter.h \
		sigdetect.h \
		EKGFramWork.h \
		header.h \
		/usr/include/qwt-qt4/qwt_plot.h \
		/usr/include/qwt-qt4/qwt_global.h \
		/usr/include/qwt-qt4/qwt_array.h \
		/usr/include/qwt-qt4/qwt_text.h \
		/usr/include/qwt-qt4/qwt_plot_dict.h \
		/usr/include/qwt-qt4/qwt_plot_item.h \
		/usr/include/qwt-qt4/qwt_legend_itemmanager.h \
		/usr/include/qwt-qt4/qwt_double_rect.h \
		/usr/include/qwt-qt4/qwt_scale_map.h \
		/usr/include/qwt-qt4/qwt_math.h \
		/usr/include/qwt-qt4/qwt_plot_printfilter.h \
		/usr/include/qwt-qt4/qwt_plot_curve.h \
		/usr/include/qwt-qt4/qwt_polygon.h \
		/usr/include/qwt-qt4/qwt_data.h \
		/usr/include/qwt-qt4/qwt_plot_zoomer.h \
		/usr/include/qwt-qt4/qwt_plot_picker.h \
		/usr/include/qwt-qt4/qwt_plot_canvas.h \
		/usr/include/qwt-qt4/qwt_picker.h \
		/usr/include/qwt-qt4/qwt_event_pattern.h \
		/usr/include/qwt-qt4/qwt_plot_panner.h \
		/usr/include/qwt-qt4/qwt_panner.h \
		/usr/include/qwt-qt4/qwt_plot_layout.h \
		/usr/include/qwt-qt4/qwt_plot_grid.h \
		/usr/include/qwt-qt4/qwt_scale_div.h \
		/usr/include/qwt-qt4/qwt_valuelist.h \
		/usr/include/qwt-qt4/qwt_double_interval.h \
		/usr/include/qwt-qt4/qwt_plot_spectrogram.h \
		/usr/include/qwt-qt4/qwt_raster_data.h \
		/usr/include/qwt-qt4/qwt_plot_rasteritem.h \
		/usr/include/qwt-qt4/qwt_scale_widget.h \
		/usr/include/qwt-qt4/qwt_scale_draw.h \
		/usr/include/qwt-qt4/qwt_abstract_scale_draw.h \
		/usr/include/qwt-qt4/qwt_symbol.h \
		/usr/include/qwt-qt4/qwt_color_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nnframwork.o nnframwork.cpp

moc_ekgwindow.o: moc_ekgwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ekgwindow.o moc_ekgwindow.cpp

moc_GButton.o: moc_GButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GButton.o moc_GButton.cpp

moc_ekgscan.o: moc_ekgscan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ekgscan.o moc_ekgscan.cpp

moc_qscan.o: moc_qscan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qscan.o moc_qscan.cpp

moc_ekgnn.o: moc_ekgnn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ekgnn.o moc_ekgnn.cpp

moc_nnframwork.o: moc_nnframwork.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nnframwork.o moc_nnframwork.cpp

qrc_EKG.o: qrc_EKG.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_EKG.o qrc_EKG.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

